"""Exp 54 — build a FEW-SHOT exemplar block from r1's own rulings.

Exp 51/52 distilled r1's judgment into WHEN->rule precedents; 3b ignored them, 14b obeyed
them and gained nothing. This asks whether the loss is in the *distillation*: show the
student raw (state -> ruling) pairs instead of rules, via the same PINS_MANUAL injection
path (referee.load_manual just splices text below PROMPT-START, no schema).

Exemplars come from the referee scene cache, which keys rulings by the scene descriptor:
  v2|referee|free4|r01:prod:behind:b1+m1|supply:r2:many|llm:deepseek-r1:32b
Only `|referee|`-tagged keys are used: those are vanilla r1, no manual installed.
"""
import collections
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "llm_agent_cache.json")
OUT = os.path.join(HERE, "referee_fewshot.md")
N = 14                      # exemplars; keep the block comparable in length to the 6-entry manual
POOL = 8                    # eval venue; drop scenes from larger-pool runs


def scenes():
    """Vanilla-r1 referee rulings with a non-trivial state, deduped by scene."""
    cache = json.load(open(CACHE))
    out = {}
    for k, v in cache.items():
        parts = k.split("|")
        if not (k.startswith("v2") and parts[1] == "referee"):
            continue                                  # manual-tagged => contaminated
        if "deepseek-r1:32b" not in k or not v.get("_source", "").startswith("llm"):
            continue
        m = re.search(r"\|free(\d+)\|", k)
        if not m or not 0 < int(m.group(1)) <= POOL:
            continue        # free0 is forced, not judgment; >POOL is another venue (Exp 48's 30-GPU runs)
        out.setdefault("|".join(parts[2:-1]), (int(m.group(1)), v))
    return out


def pick(pool):
    """Spread over free_gpus x supply pressure so the block isn't one contention regime."""
    by_cell = collections.defaultdict(list)
    for scene, (free, v) in sorted(pool.items()):
        supply = next((p for p in scene.split("|") if p.startswith("supply:")), "supply:none")
        by_cell[(free, supply.split(":")[-1])].append((scene, v))   # cell = free x incoming_prod
    # order cells so a full sweep of free_gpus comes before a second supply variant of any
    # free value: rank = how many cells of the same free_gpus precede it.
    # ...and take the high-pressure supply variants first: incoming_prod='many' at a tight
    # pool is the regime Exp 50 pinned as the referee's failure mode, so it must be shown.
    pressure = {"many": 0, "few": 1, "none": 2}
    rank, ordered = collections.Counter(), []
    for free, supply in sorted(by_cell, key=lambda c: (c[0], pressure.get(c[1].split(":")[-1], 3))):
        ordered.append((rank[free], free, supply))
        rank[free] += 1
    picked = [(free, *by_cell[(free, supply)][0])
              for _, free, supply in sorted(ordered)][:N]
    return sorted(picked)


def render(picked):
    lines = [
        "# Referee few-shot exemplars (Exp 54) — generated by pins/fewshot_build.py, do not hand-edit",
        "",
        "<!-- PROMPT-START: everything below this line is sent to the referee -->",
        "WORKED EXAMPLES from a senior referee's past rulings on this system. "
        "They are not rules: infer the judgment behind them and apply it to the scene you are given.",
        "",
    ]
    for n, (free, scene, v) in enumerate(picked, 1):
        jobs = [p for p in scene.split("|") if ":" in p and not p.startswith("supply:")]
        supply = next((p for p in scene.split("|") if p.startswith("supply:")), "supply:none")
        lines += [
            f"E{n}. SCENE: free_gpus={free}; requests=[{', '.join(jobs) or 'none'}]; "
            f"{supply.replace('supply:', 'supply_asks=')}",
            f"    RULING: reserve={v.get('reserve', 0)}, alloc={json.dumps(v.get('alloc', {}))}",
            f"    BECAUSE: {v.get('justification', '').strip()}",
            "",
        ]
    return "\n".join(lines)


if __name__ == "__main__":
    pool = scenes()
    picked = pick(pool)
    open(OUT, "w").write(render(picked))
    print(f"{len(pool)} distinct vanilla-r1 scenes -> {len(picked)} exemplars -> {OUT}")
    print("free_gpus covered:", sorted({f for f, _, _ in picked}))
